version: 2
jobs:
  build:
    environment:
      REGION: "us-east-1"
      ACCOUNTID: "389503229785"
      SRCREPO: "circle-ci-repo"
      IMGTAG: "latest"
      DSTREPO: "circle-ci-repo-stg"
    working_directory: /app
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk update && apk upgrade
            apk add --no-cache \
              py-pip
            pip install --upgrade pip
            pip install \
              docker-compose==1.12.0 \
              awscli
      - run:
          name: Get image from staging ECR
          command: |
            login="$(aws ecr get-login --no-include-email --region ${REGION} )"
            ${login}
            docker pull ${ACCOUNTID}.dkr.ecr.${REGION}.amazonaws.com/${SRCREPO}:${IMGTAG}
            docker images
      - run:
          name: Tag pulled image with destination reponame
          command: |
            docker tag ${ACCOUNTID}.dkr.ecr.${REGION}.amazonaws.com/${SRCREPO}:${IMGTAG} ${ACCOUNTID}.dkr.ecr.${REGION}.amazonaws.com/${DSTREPO}:${IMGTAG}
      - run:
          name: Push image to production ECR
          command: |
            docker push ${ACCOUNTID}.dkr.ecr.${REGION}.amazonaws.com/${DSTREPO}:${IMGTAG}
#deployment:
#  prod:
#    branch: master
#    commands:
#      - ./deploy.sh
