version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true

    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run: |
         docker login -u $DOCKER_USER -p $DOCKER_PASS
         docker run -d --name db company/proprietary-db:1.2.3
    # build the application image
      - run: docker build -t company/app:$CIRCLE_BRANCH .
    # deploy image
      - run: docker push company/app:$CIRCLE_BRANCH
