workflows:
  version: 2
  getimage-test-and-approval-deploy:
    jobs:
      - getimage:
          environment:
            - TAG: "latest"
        steps:
          - run:
              name: "Getting image with provided tag from Staging environment"
              command: |
                echo test

      - hold:
        type: approval
        requires:
          - getimage

      - pushtoprod:
        steps:
          - run:
              name: "Push image from Staging to Production..."
              command: |
                echo test
        requires:
          - hold
