version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip=9.0.0-r1
            pip install \
              docker-compose==1.12.0 \
              awscli==1.11.76
      - run:
          name: Build image
          command: |
            docker build -t goapp:latest .
            docker tag goapp:latest 389503229785.dkr.ecr.us-east-1.amazonaws.com/circle-ci-repo/goapp:latest
            docker images
      - run:
          name: Run tests
          command: |
            docker run -d -p 8080:8080 --name sample-go-webapp 389503229785.dkr.ecr.us-east-1.amazonaws.com/circle-ci-repo/goapp:latest ; sleep 10
#            curl --retry 10 --retry-delay 5 localhost:8080 | grep "Hello World!"
      - run:
          name: Push application Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              login="$(aws ecr get-login --region us-east-1 )"
              ${login}
              docker push 389503229785.dkr.ecr.us-east-1.amazonaws.com/goapp:latest
            fi
#deployment:
#  prod:
#    branch: master
#    commands:
#      - ./deploy.sh
