version: 2
jobs:
  build:
    environment:
      REGION: "us-east-1"
      ACCOUNTID: "389503229785"
      SRCREPO: "circle-ci-repo"
      IMGTAG: "latest"
      DSTREPO: "dst-repo-test"
      DSTTAG: "copiedimage"
      DSTACCOUNT: "992536150469"
    working_directory: /app
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk update && apk upgrade
            apk add --no-cache \
              py-pip
            pip install --upgrade pip
            pip install \
              awscli
      - run:
          name: Get image from staging ECR
          command: |
            login="$(aws ecr get-login --no-include-email --region ${REGION} )"
            ${login} 
            docker pull ${ACCOUNTID}.dkr.ecr.${REGION}.amazonaws.com/${SRCREPO}:${IMGTAG}
            cd /tmp
            docker save --output newversion.tar ${ACCOUNTID}.dkr.ecr.${REGION}.amazonaws.com/${SRCREPO}:${IMGTAG}
            docker images

      - store_artifacts:
          path: /tmp/newversion.tar
          destination: newversion.tar

      - run:
          name: Push image to dest account
          command: |
            login=$(aws ecr get-login --registry-ids ${DSTACCOUNT}  --region ${REGION} )
            ${login} || echo AWS use deprecated -e option
            docker tag ${ACCOUNTID}.dkr.ecr.${REGION}.amazonaws.com/${SRCREPO}:${IMGTAG} ${DSTACCOUNT}.dkr.ecr.${REGION}.amazonaws.com/${DSTREPO}:${DSTTAG}
            docker push ${DSTACCOUNT}.dkr.ecr.${REGION}.amazonaws.com/${DSTREPO}:${DSTTAG}
      - run:
          name: Tag pulled image with destination reponame
          command: |
            docker tag ${ACCOUNTID}.dkr.ecr.${REGION}.amazonaws.com/${SRCREPO}:${IMGTAG} ${ACCOUNTID}.dkr.ecr.${REGION}.amazonaws.com/${DSTREPO}:${IMGTAG}
      - run:
          name: Push image to production ECR
          command: |
            docker push ${ACCOUNTID}.dkr.ecr.${REGION}.amazonaws.com/${DSTREPO}:${IMGTAG}
workflows:
  version: 2
  get-image-wait-approval-deploy:
    jobs:
      - hold:
          type: approval
      - build:
          requires:
            - hold
